import json

import httpx
from fastapi import APIRouter, HTTPException

from config import logger, MAX_RETRIES, MATCH_THRESHOLD, get_openrouter_api_key, get_openrouter_model
from models.schemas import GenerateRequest, GenerateResponse
from services.playlist import get_git_commit, deduplicate_tracks
from services.deezer import enrich_tracks
from services.llm import build_system_prompt, call_llm

router = APIRouter()


@router.get("/version")
def version():
    return {"version": get_git_commit()}


@router.post("/api/generate", response_model=GenerateResponse)
async def generate(req: GenerateRequest):
    if not req.prompt or not req.prompt.strip():
        raise HTTPException(status_code=400, detail="Prompt is required")

    api_key = get_openrouter_api_key()
    model = get_openrouter_model()
    genre_instruction = f'Focus on the "{req.genre}" genre. ' if (req.genre and req.genre != "any") else ""

    system_prompt = build_system_prompt(
        genre_instruction=genre_instruction,
        user_prompt=req.prompt,
        count=req.count,
    )

    try:
        json_data = await call_llm(api_key, model, system_prompt, req.prompt)
        playlist_name = json_data.get("name") or json_data.get("playlist_name") or ""
        raw_tracks = json_data.get("tracks") or json_data.get("songs") or json_data.get("playlist") or []
        if not isinstance(raw_tracks, list):
            raw_tracks = []
        raw_tracks = raw_tracks[:req.count]

        if not raw_tracks:
            raise HTTPException(status_code=500, detail="No tracks generated by LLM")

        raw_tracks = deduplicate_tracks(raw_tracks)
        logger.info("After dedup: %d unique tracks", len(raw_tracks))

        enriched, failed = await enrich_tracks(raw_tracks)
        retries = 0

        while failed and len(enriched) / len(raw_tracks) <= MATCH_THRESHOLD and retries < MAX_RETRIES:
            retries += 1
            logger.info(
                "Retry %d/%d: matched %d/%d tracks. Replacing %d failed tracks.",
                retries, MAX_RETRIES, len(enriched), len(raw_tracks), len(failed),
            )
            retry_prompt = build_system_prompt(
                genre_instruction=genre_instruction,
                user_prompt=req.prompt,
                count=req.count - len(enriched),
                is_retry=True,
                failed_tracks=failed,
            )
            try:
                retry_json = await call_llm(api_key, model, retry_prompt, req.prompt)
                retry_raw = retry_json.get("tracks") or retry_json.get("songs") or retry_json.get("playlist") or []
                if isinstance(retry_raw, list):
                    retry_raw = deduplicate_tracks(retry_raw)
                    retry_enriched, retry_failed = await enrich_tracks(retry_raw)
                    enriched.extend(retry_enriched)
                    failed = retry_failed
                else:
                    break
            except (httpx.RequestError, json.JSONDecodeError, ValueError) as e:
                logger.error("Retry %d failed: %s", retries, e)
                break

        return GenerateResponse(
            name=playlist_name,
            tracks=enriched,
            total=len(raw_tracks),
            matched=len(enriched),
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error("Generation failed: %s", e, exc_info=True)
        raise HTTPException(status_code=500, detail=str(e)) from e
